server:
  port: 8081

info:
  application:
    name: ${project.name}
    version: ${project.version}
    description: ${project.description}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://individuals-keycloak:8080/realms/individuals/protocol/openid-connect/certs

keycloak:
  admin:
    auth-server-url: http://individuals-keycloak:8080
    realm: individuals
    client-id: individuals-api
    client-secret: ваш_секрет_из_realm-export.json

application:
  individuals-api:
    rest:
      connection-timeout: 5000
    swagger:
      local-server: http://localhost
      dev-server: https://individuals-api.dns.by

management:
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: ALWAYS
