info:
  application:
    name: ${project.name}
    version: ${project.version}
    description: ${project.description}

server:
  port: 8081

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/psp/protocol/openid-connect/certs

application:
  individuals-api:
    rest:
      connection-timeout: 5000
    swagger:
      local-server: http://localhost
      dev-server: https://individuals-api.dns.by

#keycloak:
#  auth-server-url: https://your-keycloak/auth
#  realm: your-realm
#  public:
#    client-id: your-public-client
#  admin:
#    client-id: your-admin-client
#    client-secret: your-admin-secret